"""Multi-Format IaC Export Engine.

Converts FaultRay infrastructure definitions and recommendations into
actual Infrastructure-as-Code files that teams can directly apply.

Supported formats:
- Terraform HCL
- AWS CloudFormation YAML
- Kubernetes manifests
- Docker Compose YAML
- Ansible playbook YAML
- Pulumi (Python)
"""

from __future__ import annotations

import re
import textwrap
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from faultray.model.components import Component, ComponentType
from faultray.model.graph import InfraGraph


# ---------------------------------------------------------------------------
# Enums and dataclasses
# ---------------------------------------------------------------------------


class IaCFormat(str, Enum):
    """Supported IaC output formats."""

    TERRAFORM = "terraform"
    CLOUDFORMATION = "cloudformation"
    KUBERNETES = "kubernetes"
    DOCKER_COMPOSE = "docker_compose"
    ANSIBLE = "ansible"
    PULUMI_PYTHON = "pulumi_python"


@dataclass
class IaCExportResult:
    """Result of an IaC export operation."""

    format: IaCFormat
    files: dict[str, str] = field(default_factory=dict)  # filename -> content
    warnings: list[str] = field(default_factory=list)
    unsupported_components: list[str] = field(default_factory=list)
    readme: str = ""


# ---------------------------------------------------------------------------
# Helper: sanitise resource names for IaC identifiers
# ---------------------------------------------------------------------------

def _sanitize_id(name: str) -> str:
    """Turn a component id into a safe IaC identifier (alphanumeric + underscores)."""
    return re.sub(r"[^a-zA-Z0-9]", "_", name).strip("_").lower()


def _sanitize_k8s_name(name: str) -> str:
    """Turn a component id into a valid Kubernetes resource name (lowercase, dashes)."""
    return re.sub(r"[^a-z0-9-]", "-", name.lower()).strip("-")


# ---------------------------------------------------------------------------
# Port mapping helpers
# ---------------------------------------------------------------------------

_DEFAULT_PORT: dict[ComponentType, int] = {
    ComponentType.LOAD_BALANCER: 80,
    ComponentType.WEB_SERVER: 80,
    ComponentType.APP_SERVER: 8080,
    ComponentType.DATABASE: 5432,
    ComponentType.CACHE: 6379,
    ComponentType.QUEUE: 5672,
    ComponentType.STORAGE: 9000,
    ComponentType.DNS: 53,
    ComponentType.EXTERNAL_API: 443,
    ComponentType.CUSTOM: 8080,
}

_DEFAULT_IMAGE: dict[ComponentType, str] = {
    ComponentType.LOAD_BALANCER: "nginx:1.25-alpine",
    ComponentType.WEB_SERVER: "nginx:1.25-alpine",
    ComponentType.APP_SERVER: "node:20-alpine",
    ComponentType.DATABASE: "postgres:16-alpine",
    ComponentType.CACHE: "redis:7-alpine",
    ComponentType.QUEUE: "rabbitmq:3-management-alpine",
    ComponentType.STORAGE: "minio/minio:latest",
    ComponentType.DNS: "coredns/coredns:1.11",
    ComponentType.EXTERNAL_API: "alpine:3.19",
    ComponentType.CUSTOM: "alpine:3.19",
}


def _comp_port(comp: Component) -> int:
    """Return the effective port for a component."""
    return comp.port if comp.port > 0 else _DEFAULT_PORT.get(comp.type, 8080)


# ---------------------------------------------------------------------------
# Terraform templates
# ---------------------------------------------------------------------------

_TF_HEADER = textwrap.dedent("""\
    # ------------------------------------------------------------------
    # FaultRay — Auto-generated Terraform configuration
    # ------------------------------------------------------------------
    #
    # This file was generated by FaultZero IaC Export Engine.
    # Review before applying.
    #
    # Usage:
    #   terraform init
    #   terraform plan
    #   terraform apply
    # ------------------------------------------------------------------

    terraform {
      required_version = ">= 1.5"
      required_providers {
        aws = {
          source  = "hashicorp/aws"
          version = "~> 5.0"
        }
      }
    }

    provider "aws" {
      region = var.aws_region
    }

    variable "aws_region" {
      description = "AWS region for resource deployment"
      type        = string
      default     = "us-east-1"
    }

    variable "environment" {
      description = "Deployment environment name"
      type        = string
      default     = "production"
    }

    locals {
      common_tags = {
        "managed-by"  = "faultzero"
        "environment" = var.environment
      }
    }
""")


def _tf_load_balancer(comp: Component, sid: str) -> str:
    port = _comp_port(comp)
    multi_az = "true" if comp.replicas > 1 else "false"
    return textwrap.dedent(f"""\

        # --- Load Balancer: {comp.name} ---
        resource "aws_lb" "{sid}" {{
          name               = "{sid}"
          internal           = false
          load_balancer_type = "application"
          security_groups    = [aws_security_group.{sid}_sg.id]
          subnets            = var.subnet_ids
          enable_cross_zone_load_balancing = {multi_az}

          tags = merge(local.common_tags, {{
            Name = "{comp.name}"
          }})
        }}

        resource "aws_lb_target_group" "{sid}_tg" {{
          name     = "{sid}-tg"
          port     = {port}
          protocol = "HTTP"
          vpc_id   = var.vpc_id

          health_check {{
            enabled             = true
            healthy_threshold   = 3
            unhealthy_threshold = 3
            timeout             = 5
            interval            = 30
            path                = "/health"
            protocol            = "HTTP"
            matcher             = "200"
          }}

          tags = merge(local.common_tags, {{
            Name = "{comp.name}-tg"
          }})
        }}

        resource "aws_lb_listener" "{sid}_listener" {{
          load_balancer_arn = aws_lb.{sid}.arn
          port              = {port}
          protocol          = "HTTP"

          default_action {{
            type             = "forward"
            target_group_arn = aws_lb_target_group.{sid}_tg.arn
          }}
        }}

        resource "aws_security_group" "{sid}_sg" {{
          name        = "{sid}-sg"
          description = "Security group for {comp.name}"
          vpc_id      = var.vpc_id

          ingress {{
            from_port   = {port}
            to_port     = {port}
            protocol    = "tcp"
            cidr_blocks = ["0.0.0.0/0"]
            description = "Allow inbound traffic on port {port}"
          }}

          egress {{
            from_port   = 0
            to_port     = 0
            protocol    = "-1"
            cidr_blocks = ["0.0.0.0/0"]
            description = "Allow all outbound traffic"
          }}

          tags = merge(local.common_tags, {{
            Name = "{comp.name}-sg"
          }})
        }}
    """)


def _tf_server(comp: Component, sid: str) -> str:
    port = _comp_port(comp)
    replicas = max(comp.replicas, 1)
    autoscale_block = ""
    if comp.autoscaling.enabled:
        autoscale_block = textwrap.dedent(f"""

        resource "aws_appautoscaling_target" "{sid}_target" {{
          max_capacity       = {comp.autoscaling.max_replicas}
          min_capacity       = {comp.autoscaling.min_replicas}
          resource_id        = "service/${{aws_ecs_cluster.main.name}}/${{aws_ecs_service.{sid}.name}}"
          scalable_dimension = "ecs:service:DesiredCount"
          service_namespace  = "ecs"
        }}

        resource "aws_appautoscaling_policy" "{sid}_cpu_scaling" {{
          name               = "{sid}-cpu-scaling"
          policy_type        = "TargetTrackingScaling"
          resource_id        = aws_appautoscaling_target.{sid}_target.resource_id
          scalable_dimension = aws_appautoscaling_target.{sid}_target.scalable_dimension
          service_namespace  = aws_appautoscaling_target.{sid}_target.service_namespace

          target_tracking_scaling_policy_configuration {{
            predefined_metric_specification {{
              predefined_metric_type = "ECSServiceAverageCPUUtilization"
            }}
            target_value       = {comp.autoscaling.scale_up_threshold}
            scale_in_cooldown  = {comp.autoscaling.scale_down_delay_seconds}
            scale_out_cooldown = {comp.autoscaling.scale_up_delay_seconds}
          }}
        }}
        """)

    return textwrap.dedent(f"""\

        # --- Server / Service: {comp.name} ---
        resource "aws_ecs_service" "{sid}" {{
          name            = "{sid}"
          cluster         = aws_ecs_cluster.main.id
          task_definition = aws_ecs_task_definition.{sid}.arn
          desired_count   = {replicas}
          launch_type     = "FARGATE"

          network_configuration {{
            subnets          = var.subnet_ids
            security_groups  = [aws_security_group.{sid}_sg.id]
            assign_public_ip = false
          }}

          tags = merge(local.common_tags, {{
            Name = "{comp.name}"
          }})
        }}

        resource "aws_ecs_task_definition" "{sid}" {{
          family                   = "{sid}"
          network_mode             = "awsvpc"
          requires_compatibilities = ["FARGATE"]
          cpu                      = "256"
          memory                   = "512"

          container_definitions = jsonencode([{{
            name      = "{sid}"
            image     = var.{sid}_image
            essential = true
            portMappings = [{{
              containerPort = {port}
              hostPort      = {port}
              protocol      = "tcp"
            }}]
            healthCheck = {{
              command     = ["CMD-SHELL", "curl -f http://localhost:{port}/health || exit 1"]
              interval    = 30
              timeout     = 5
              retries     = 3
              startPeriod = 60
            }}
            logConfiguration = {{
              logDriver = "awslogs"
              options = {{
                "awslogs-group"         = "/ecs/{sid}"
                "awslogs-region"        = var.aws_region
                "awslogs-stream-prefix" = "ecs"
              }}
            }}
          }}])

          tags = merge(local.common_tags, {{
            Name = "{comp.name}"
          }})
        }}

        resource "aws_security_group" "{sid}_sg" {{
          name        = "{sid}-sg"
          description = "Security group for {comp.name}"
          vpc_id      = var.vpc_id

          ingress {{
            from_port   = {port}
            to_port     = {port}
            protocol    = "tcp"
            self        = true
            description = "Allow internal service traffic"
          }}

          egress {{
            from_port   = 0
            to_port     = 0
            protocol    = "-1"
            cidr_blocks = ["0.0.0.0/0"]
            description = "Allow all outbound traffic"
          }}

          tags = merge(local.common_tags, {{
            Name = "{comp.name}-sg"
          }})
        }}

        variable "{sid}_image" {{
          description = "Container image for {comp.name}"
          type        = string
          default     = "{_DEFAULT_IMAGE.get(comp.type, 'alpine:3.19')}"
        }}
    """) + autoscale_block


def _tf_database(comp: Component, sid: str) -> str:
    return textwrap.dedent(f"""\

        # --- Database: {comp.name} ---
        resource "aws_rds_cluster" "{sid}" {{
          cluster_identifier = "{sid}"
          engine             = "aurora-postgresql"
          engine_version     = "15.4"
          database_name      = "{sid}"
          master_username    = var.{sid}_master_username
          master_password    = var.{sid}_master_password
          storage_encrypted  = true

          vpc_security_group_ids = [aws_security_group.{sid}_sg.id]
          db_subnet_group_name   = aws_db_subnet_group.{sid}.name

          backup_retention_period = 7
          preferred_backup_window = "03:00-04:00"

          tags = merge(local.common_tags, {{
            Name = "{comp.name}"
          }})
        }}

        resource "aws_rds_cluster_instance" "{sid}_instances" {{
          count              = {max(comp.replicas, 1)}
          identifier         = "{sid}-${{count.index}}"
          cluster_identifier = aws_rds_cluster.{sid}.id
          instance_class     = "db.r6g.large"
          engine             = aws_rds_cluster.{sid}.engine
          engine_version     = aws_rds_cluster.{sid}.engine_version

          tags = merge(local.common_tags, {{
            Name = "{comp.name}-${{count.index}}"
          }})
        }}

        resource "aws_db_subnet_group" "{sid}" {{
          name       = "{sid}-subnet-group"
          subnet_ids = var.subnet_ids

          tags = merge(local.common_tags, {{
            Name = "{comp.name}-subnet-group"
          }})
        }}

        resource "aws_security_group" "{sid}_sg" {{
          name        = "{sid}-sg"
          description = "Security group for {comp.name}"
          vpc_id      = var.vpc_id

          ingress {{
            from_port   = {_comp_port(comp)}
            to_port     = {_comp_port(comp)}
            protocol    = "tcp"
            self        = true
            description = "Allow database connections"
          }}

          egress {{
            from_port   = 0
            to_port     = 0
            protocol    = "-1"
            cidr_blocks = ["0.0.0.0/0"]
          }}

          tags = merge(local.common_tags, {{
            Name = "{comp.name}-sg"
          }})
        }}

        variable "{sid}_master_username" {{
          description = "Master username for {comp.name}"
          type        = string
          default     = "admin"
          sensitive   = true
        }}

        variable "{sid}_master_password" {{
          description = "Master password for {comp.name}"
          type        = string
          sensitive   = true
        }}
    """)


def _tf_cache(comp: Component, sid: str) -> str:
    replicas = max(comp.replicas, 1)
    return textwrap.dedent(f"""\

        # --- Cache: {comp.name} ---
        resource "aws_elasticache_replication_group" "{sid}" {{
          replication_group_id       = "{sid}"
          description                = "Redis cache for {comp.name}"
          node_type                  = "cache.r6g.large"
          num_cache_clusters         = {replicas}
          automatic_failover_enabled = {"true" if replicas > 1 else "false"}
          engine                     = "redis"
          engine_version             = "7.0"
          port                       = {_comp_port(comp)}
          at_rest_encryption_enabled = true
          transit_encryption_enabled = true

          subnet_group_name  = aws_elasticache_subnet_group.{sid}.name
          security_group_ids = [aws_security_group.{sid}_sg.id]

          tags = merge(local.common_tags, {{
            Name = "{comp.name}"
          }})
        }}

        resource "aws_elasticache_subnet_group" "{sid}" {{
          name       = "{sid}-subnet-group"
          subnet_ids = var.subnet_ids
        }}

        resource "aws_security_group" "{sid}_sg" {{
          name        = "{sid}-sg"
          description = "Security group for {comp.name}"
          vpc_id      = var.vpc_id

          ingress {{
            from_port   = {_comp_port(comp)}
            to_port     = {_comp_port(comp)}
            protocol    = "tcp"
            self        = true
            description = "Allow Redis connections"
          }}

          egress {{
            from_port   = 0
            to_port     = 0
            protocol    = "-1"
            cidr_blocks = ["0.0.0.0/0"]
          }}

          tags = merge(local.common_tags, {{
            Name = "{comp.name}-sg"
          }})
        }}
    """)


def _tf_queue(comp: Component, sid: str) -> str:
    return textwrap.dedent(f"""\

        # --- Message Queue: {comp.name} ---
        resource "aws_sqs_queue" "{sid}" {{
          name                       = "{sid}"
          visibility_timeout_seconds = 30
          message_retention_seconds  = 1209600  # 14 days
          receive_wait_time_seconds  = 10       # Long polling

          tags = merge(local.common_tags, {{
            Name = "{comp.name}"
          }})
        }}

        resource "aws_sqs_queue" "{sid}_dlq" {{
          name                      = "{sid}-dlq"
          message_retention_seconds = 1209600

          tags = merge(local.common_tags, {{
            Name = "{comp.name}-DLQ"
          }})
        }}

        resource "aws_sqs_queue_redrive_policy" "{sid}" {{
          queue_url = aws_sqs_queue.{sid}.id
          redrive_policy = jsonencode({{
            deadLetterTargetArn = aws_sqs_queue.{sid}_dlq.arn
            maxReceiveCount     = 5
          }})
        }}
    """)


def _tf_storage(comp: Component, sid: str) -> str:
    return textwrap.dedent(f"""\

        # --- Object Storage: {comp.name} ---
        resource "aws_s3_bucket" "{sid}" {{
          bucket = "{sid}-${{var.environment}}"

          tags = merge(local.common_tags, {{
            Name = "{comp.name}"
          }})
        }}

        resource "aws_s3_bucket_versioning" "{sid}" {{
          bucket = aws_s3_bucket.{sid}.id
          versioning_configuration {{
            status = "Enabled"
          }}
        }}

        resource "aws_s3_bucket_server_side_encryption_configuration" "{sid}" {{
          bucket = aws_s3_bucket.{sid}.id
          rule {{
            apply_server_side_encryption_by_default {{
              sse_algorithm = "aws:kms"
            }}
          }}
        }}

        resource "aws_s3_bucket_public_access_block" "{sid}" {{
          bucket = aws_s3_bucket.{sid}.id

          block_public_acls       = true
          block_public_policy     = true
          ignore_public_acls      = true
          restrict_public_buckets = true
        }}
    """)


def _tf_dns(comp: Component, sid: str) -> str:
    return textwrap.dedent(f"""\

        # --- DNS: {comp.name} ---
        resource "aws_route53_zone" "{sid}" {{
          name = "{sid}.example.com"

          tags = merge(local.common_tags, {{
            Name = "{comp.name}"
          }})
        }}

        resource "aws_route53_health_check" "{sid}" {{
          fqdn              = "{sid}.example.com"
          port              = 443
          type              = "HTTPS"
          resource_path     = "/health"
          failure_threshold = 3
          request_interval  = 30
          measure_latency   = true

          tags = merge(local.common_tags, {{
            Name = "{comp.name}-healthcheck"
          }})
        }}
    """)


def _tf_generic(comp: Component, sid: str) -> str:
    """Fallback Terraform template for unmapped component types."""
    port = _comp_port(comp)
    return textwrap.dedent(f"""\

        # --- {comp.type.value}: {comp.name} ---
        # NOTE: This component type ({comp.type.value}) has no specialised
        # Terraform mapping. A generic ECS service is generated as a placeholder.
        resource "aws_ecs_service" "{sid}" {{
          name            = "{sid}"
          cluster         = aws_ecs_cluster.main.id
          task_definition = aws_ecs_task_definition.{sid}.arn
          desired_count   = {max(comp.replicas, 1)}
          launch_type     = "FARGATE"

          network_configuration {{
            subnets          = var.subnet_ids
            security_groups  = [aws_security_group.{sid}_sg.id]
            assign_public_ip = false
          }}

          tags = merge(local.common_tags, {{
            Name = "{comp.name}"
          }})
        }}

        resource "aws_ecs_task_definition" "{sid}" {{
          family                   = "{sid}"
          network_mode             = "awsvpc"
          requires_compatibilities = ["FARGATE"]
          cpu                      = "256"
          memory                   = "512"

          container_definitions = jsonencode([{{
            name      = "{sid}"
            image     = "{_DEFAULT_IMAGE.get(comp.type, 'alpine:3.19')}"
            essential = true
            portMappings = [{{
              containerPort = {port}
              hostPort      = {port}
              protocol      = "tcp"
            }}]
          }}])

          tags = merge(local.common_tags, {{
            Name = "{comp.name}"
          }})
        }}

        resource "aws_security_group" "{sid}_sg" {{
          name        = "{sid}-sg"
          vpc_id      = var.vpc_id

          ingress {{
            from_port   = {port}
            to_port     = {port}
            protocol    = "tcp"
            self        = true
          }}

          egress {{
            from_port   = 0
            to_port     = 0
            protocol    = "-1"
            cidr_blocks = ["0.0.0.0/0"]
          }}

          tags = merge(local.common_tags, {{
            Name = "{comp.name}-sg"
          }})
        }}
    """)


_TF_RENDERER: dict[ComponentType, Any] = {
    ComponentType.LOAD_BALANCER: _tf_load_balancer,
    ComponentType.WEB_SERVER: _tf_server,
    ComponentType.APP_SERVER: _tf_server,
    ComponentType.DATABASE: _tf_database,
    ComponentType.CACHE: _tf_cache,
    ComponentType.QUEUE: _tf_queue,
    ComponentType.STORAGE: _tf_storage,
    ComponentType.DNS: _tf_dns,
}


# ---------------------------------------------------------------------------
# Kubernetes templates
# ---------------------------------------------------------------------------

def _k8s_deployment(comp: Component, kname: str) -> str:
    port = _comp_port(comp)
    replicas = max(comp.replicas, 1)
    image = _DEFAULT_IMAGE.get(comp.type, "alpine:3.19")
    return textwrap.dedent(f"""\
        # --- Deployment: {comp.name} ---
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: {kname}
          labels:
            app: {kname}
            managed-by: faultzero
        spec:
          replicas: {replicas}
          selector:
            matchLabels:
              app: {kname}
          template:
            metadata:
              labels:
                app: {kname}
            spec:
              containers:
              - name: {kname}
                image: {image}
                ports:
                - containerPort: {port}
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /health
                    port: {port}
                  initialDelaySeconds: 10
                  periodSeconds: 10
                livenessProbe:
                  httpGet:
                    path: /health
                    port: {port}
                  initialDelaySeconds: 30
                  periodSeconds: 15
                resources:
                  requests:
                    cpu: "100m"
                    memory: "128Mi"
                  limits:
                    cpu: "500m"
                    memory: "512Mi"
    """)


def _k8s_statefulset(comp: Component, kname: str) -> str:
    port = _comp_port(comp)
    replicas = max(comp.replicas, 1)
    image = _DEFAULT_IMAGE.get(comp.type, "alpine:3.19")
    return textwrap.dedent(f"""\
        # --- StatefulSet: {comp.name} ---
        apiVersion: apps/v1
        kind: StatefulSet
        metadata:
          name: {kname}
          labels:
            app: {kname}
            managed-by: faultzero
        spec:
          replicas: {replicas}
          serviceName: {kname}
          selector:
            matchLabels:
              app: {kname}
          template:
            metadata:
              labels:
                app: {kname}
            spec:
              containers:
              - name: {kname}
                image: {image}
                ports:
                - containerPort: {port}
                  protocol: TCP
                volumeMounts:
                - name: data
                  mountPath: /data
                resources:
                  requests:
                    cpu: "250m"
                    memory: "512Mi"
                  limits:
                    cpu: "1000m"
                    memory: "2Gi"
          volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
    """)


def _k8s_service(comp: Component, kname: str, svc_type: str = "ClusterIP") -> str:
    port = _comp_port(comp)
    return textwrap.dedent(f"""\
        ---
        # --- Service: {comp.name} ---
        apiVersion: v1
        kind: Service
        metadata:
          name: {kname}
          labels:
            app: {kname}
            managed-by: faultzero
        spec:
          type: {svc_type}
          selector:
            app: {kname}
          ports:
          - port: {port}
            targetPort: {port}
            protocol: TCP
    """)


def _k8s_hpa(comp: Component, kname: str) -> str:
    if not comp.autoscaling.enabled:
        return ""
    return textwrap.dedent(f"""\
        ---
        # --- HPA: {comp.name} ---
        apiVersion: autoscaling/v2
        kind: HorizontalPodAutoscaler
        metadata:
          name: {kname}-hpa
          labels:
            managed-by: faultzero
        spec:
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: {kname}
          minReplicas: {comp.autoscaling.min_replicas}
          maxReplicas: {comp.autoscaling.max_replicas}
          metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: {int(comp.autoscaling.scale_up_threshold)}
    """)


def _k8s_ingress(comp: Component, kname: str) -> str:
    port = _comp_port(comp)
    return textwrap.dedent(f"""\
        ---
        # --- Ingress: {comp.name} ---
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: {kname}-ingress
          labels:
            managed-by: faultzero
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
        spec:
          ingressClassName: nginx
          rules:
          - host: {kname}.example.com
            http:
              paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: {kname}
                    port:
                      number: {port}
    """)


# ---------------------------------------------------------------------------
# CloudFormation templates
# ---------------------------------------------------------------------------

def _cfn_resource(comp: Component, sid: str) -> str:
    """Generate a CloudFormation resource block for a component."""
    port = _comp_port(comp)
    replicas = max(comp.replicas, 1)

    if comp.type == ComponentType.DATABASE:
        return textwrap.dedent(f"""\
          # --- Database: {comp.name} ---
          {sid}DBCluster:
            Type: AWS::RDS::DBCluster
            Properties:
              Engine: aurora-postgresql
              EngineVersion: "15.4"
              DatabaseName: {sid}
              MasterUsername: !Ref {sid}MasterUsername
              MasterUserPassword: !Ref {sid}MasterPassword
              StorageEncrypted: true
              BackupRetentionPeriod: 7
              Tags:
                - Key: managed-by
                  Value: faultzero
                - Key: Name
                  Value: {comp.name}

          {sid}DBInstance:
            Type: AWS::RDS::DBInstance
            Properties:
              DBClusterIdentifier: !Ref {sid}DBCluster
              DBInstanceClass: db.r6g.large
              Engine: aurora-postgresql

          {sid}MasterUsername:
            Type: AWS::SSM::Parameter
            Properties:
              Type: String
              Value: admin

          {sid}MasterPassword:
            Type: AWS::SSM::Parameter
            Properties:
              Type: String
              Value: CHANGE_ME
        """)

    if comp.type == ComponentType.CACHE:
        return textwrap.dedent(f"""\
          # --- Cache: {comp.name} ---
          {sid}CacheCluster:
            Type: AWS::ElastiCache::ReplicationGroup
            Properties:
              ReplicationGroupDescription: "Cache for {comp.name}"
              NumCacheClusters: {replicas}
              Engine: redis
              CacheNodeType: cache.r6g.large
              AutomaticFailoverEnabled: {"true" if replicas > 1 else "false"}
              AtRestEncryptionEnabled: true
              TransitEncryptionEnabled: true
              Tags:
                - Key: managed-by
                  Value: faultzero
        """)

    if comp.type == ComponentType.QUEUE:
        return textwrap.dedent(f"""\
          # --- Queue: {comp.name} ---
          {sid}Queue:
            Type: AWS::SQS::Queue
            Properties:
              QueueName: {sid}
              VisibilityTimeout: 30
              MessageRetentionPeriod: 1209600
              RedrivePolicy:
                deadLetterTargetArn: !GetAtt {sid}DLQ.Arn
                maxReceiveCount: 5
              Tags:
                - Key: managed-by
                  Value: faultzero

          {sid}DLQ:
            Type: AWS::SQS::Queue
            Properties:
              QueueName: {sid}-dlq
        """)

    if comp.type == ComponentType.STORAGE:
        return textwrap.dedent(f"""\
          # --- Storage: {comp.name} ---
          {sid}Bucket:
            Type: AWS::S3::Bucket
            Properties:
              BucketName: !Sub "{sid}-${{AWS::AccountId}}"
              VersioningConfiguration:
                Status: Enabled
              BucketEncryption:
                ServerSideEncryptionConfiguration:
                  - ServerSideEncryptionByDefault:
                      SSEAlgorithm: aws:kms
              PublicAccessBlockConfiguration:
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true
              Tags:
                - Key: managed-by
                  Value: faultzero
        """)

    if comp.type == ComponentType.LOAD_BALANCER:
        return textwrap.dedent(f"""\
          # --- Load Balancer: {comp.name} ---
          {sid}ALB:
            Type: AWS::ElasticLoadBalancingV2::LoadBalancer
            Properties:
              Name: {sid}
              Scheme: internet-facing
              Type: application
              SecurityGroups:
                - !Ref {sid}SG
              Subnets: !Ref SubnetIds
              Tags:
                - Key: managed-by
                  Value: faultzero

          {sid}SG:
            Type: AWS::EC2::SecurityGroup
            Properties:
              GroupDescription: "SG for {comp.name}"
              VpcId: !Ref VpcId
              SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: {port}
                  ToPort: {port}
                  CidrIp: 0.0.0.0/0
        """)

    # Default: ECS Service
    return textwrap.dedent(f"""\
          # --- Service: {comp.name} ---
          {sid}Service:
            Type: AWS::ECS::Service
            Properties:
              Cluster: !Ref ECSCluster
              DesiredCount: {replicas}
              LaunchType: FARGATE
              TaskDefinition: !Ref {sid}TaskDef
              Tags:
                - Key: managed-by
                  Value: faultzero

          {sid}TaskDef:
            Type: AWS::ECS::TaskDefinition
            Properties:
              Family: {sid}
              Cpu: "256"
              Memory: "512"
              NetworkMode: awsvpc
              RequiresCompatibilities:
                - FARGATE
              ContainerDefinitions:
                - Name: {sid}
                  Image: {_DEFAULT_IMAGE.get(comp.type, 'alpine:3.19')}
                  PortMappings:
                    - ContainerPort: {port}
    """)


# ---------------------------------------------------------------------------
# Docker Compose templates
# ---------------------------------------------------------------------------

def _dc_service(comp: Component, graph: InfraGraph) -> str:
    port = _comp_port(comp)
    image = _DEFAULT_IMAGE.get(comp.type, "alpine:3.19")
    kname = _sanitize_k8s_name(comp.id)

    depends_on_items = []
    for dep_comp in graph.get_dependencies(comp.id):
        dep_name = _sanitize_k8s_name(dep_comp.id)
        depends_on_items.append(f"      {dep_name}:\n        condition: service_healthy")

    depends_section = ""
    if depends_on_items:
        depends_section = "    depends_on:\n" + "\n".join(depends_on_items)

    replicas_section = ""
    if comp.replicas > 1:
        replicas_section = f"""\
    deploy:
      replicas: {comp.replicas}
      restart_policy:
        condition: on-failure
        max_attempts: 3"""

    healthcheck = f"""\
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:{port}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s"""

    volume_section = ""
    if comp.type in (ComponentType.DATABASE, ComponentType.STORAGE):
        volume_section = f"""\
    volumes:
      - {kname}_data:/data"""

    lines = [f"  # --- {comp.name} ---"]
    lines.append(f"  {kname}:")
    lines.append(f"    image: {image}")
    lines.append(f"    container_name: {kname}")
    lines.append("    ports:")
    lines.append(f'      - "{port}:{port}"')
    lines.append(healthcheck)
    if replicas_section:
        lines.append(replicas_section)
    if volume_section:
        lines.append(volume_section)
    if depends_section:
        lines.append(depends_section)
    lines.append("    networks:")
    lines.append("      - faultzero")
    lines.append("    labels:")
    lines.append("      managed-by: faultzero")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Ansible templates
# ---------------------------------------------------------------------------

def _ansible_task(comp: Component) -> str:
    kname = _sanitize_k8s_name(comp.id)
    image = _DEFAULT_IMAGE.get(comp.type, "alpine:3.19")
    port = _comp_port(comp)

    return textwrap.dedent(f"""\
        # --- {comp.name} ---
        - name: "Deploy {comp.name}"
          community.docker.docker_container:
            name: "{kname}"
            image: "{image}"
            state: started
            restart_policy: unless-stopped
            ports:
              - "{port}:{port}"
            labels:
              managed-by: faultzero
            healthcheck:
              test: ["CMD", "wget", "--spider", "-q", "http://localhost:{port}/health"]
              interval: 30s
              timeout: 10s
              retries: 3
          tags:
            - deploy
            - {comp.type.value}
    """)


# ---------------------------------------------------------------------------
# Pulumi (Python) templates
# ---------------------------------------------------------------------------

def _pulumi_resource(comp: Component, sid: str) -> str:
    port = _comp_port(comp)
    replicas = max(comp.replicas, 1)

    if comp.type == ComponentType.DATABASE:
        return textwrap.dedent(f"""\

        # --- Database: {comp.name} ---
        {sid}_cluster = aws.rds.Cluster(
            "{sid}",
            engine="aurora-postgresql",
            engine_version="15.4",
            database_name="{sid}",
            master_username="{sid}_admin",
            master_password=config.require_secret("{sid}_password"),
            storage_encrypted=True,
            backup_retention_period=7,
            tags={{**common_tags, "Name": "{comp.name}"}},
        )

        {sid}_instances = [
            aws.rds.ClusterInstance(
                f"{sid}-{{i}}",
                cluster_identifier={sid}_cluster.id,
                instance_class="db.r6g.large",
                engine={sid}_cluster.engine,
                tags={{**common_tags, "Name": f"{comp.name}-{{i}}"}},
            )
            for i in range({replicas})
        ]
        """)

    if comp.type == ComponentType.CACHE:
        return textwrap.dedent(f"""\

        # --- Cache: {comp.name} ---
        {sid}_cache = aws.elasticache.ReplicationGroup(
            "{sid}",
            replication_group_description="Cache for {comp.name}",
            node_type="cache.r6g.large",
            num_cache_clusters={replicas},
            automatic_failover_enabled={"True" if replicas > 1 else "False"},
            engine="redis",
            at_rest_encryption_enabled=True,
            transit_encryption_enabled=True,
            tags={{**common_tags, "Name": "{comp.name}"}},
        )
        """)

    if comp.type == ComponentType.QUEUE:
        return textwrap.dedent(f"""\

        # --- Queue: {comp.name} ---
        {sid}_dlq = aws.sqs.Queue(
            "{sid}-dlq",
            message_retention_seconds=1209600,
            tags={{**common_tags, "Name": "{comp.name}-DLQ"}},
        )

        {sid}_queue = aws.sqs.Queue(
            "{sid}",
            visibility_timeout_seconds=30,
            message_retention_seconds=1209600,
            redrive_policy=pulumi.Output.all({sid}_dlq.arn).apply(
                lambda args: json.dumps({{"deadLetterTargetArn": args[0], "maxReceiveCount": 5}})
            ),
            tags={{**common_tags, "Name": "{comp.name}"}},
        )
        """)

    if comp.type == ComponentType.STORAGE:
        return textwrap.dedent(f"""\

        # --- Storage: {comp.name} ---
        {sid}_bucket = aws.s3.BucketV2(
            "{sid}",
            tags={{**common_tags, "Name": "{comp.name}"}},
        )

        aws.s3.BucketVersioningV2(
            "{sid}-versioning",
            bucket={sid}_bucket.id,
            versioning_configuration=aws.s3.BucketVersioningV2VersioningConfigurationArgs(
                status="Enabled",
            ),
        )

        aws.s3.BucketServerSideEncryptionConfigurationV2(
            "{sid}-encryption",
            bucket={sid}_bucket.id,
            rules=[aws.s3.BucketServerSideEncryptionConfigurationV2RuleArgs(
                apply_server_side_encryption_by_default=aws.s3.BucketServerSideEncryptionConfigurationV2RuleApplyServerSideEncryptionByDefaultArgs(
                    sse_algorithm="aws:kms",
                ),
            )],
        )
        """)

    # Default: ECS service
    return textwrap.dedent(f"""\

        # --- Service: {comp.name} ---
        {sid}_task = aws.ecs.TaskDefinition(
            "{sid}",
            family="{sid}",
            cpu="256",
            memory="512",
            network_mode="awsvpc",
            requires_compatibilities=["FARGATE"],
            container_definitions=json.dumps([{{
                "name": "{sid}",
                "image": "{_DEFAULT_IMAGE.get(comp.type, 'alpine:3.19')}",
                "essential": True,
                "portMappings": [{{"containerPort": {port}, "protocol": "tcp"}}],
            }}]),
            tags={{**common_tags, "Name": "{comp.name}"}},
        )

        {sid}_service = aws.ecs.Service(
            "{sid}-svc",
            cluster=ecs_cluster.arn,
            task_definition={sid}_task.arn,
            desired_count={replicas},
            launch_type="FARGATE",
            tags={{**common_tags, "Name": "{comp.name}"}},
        )
    """)


# ---------------------------------------------------------------------------
# IaCExporter class
# ---------------------------------------------------------------------------

class IaCExporter:
    """Export an InfraGraph to various IaC formats."""

    # ---- public dispatch ---------------------------------------------------

    def export(self, graph: InfraGraph, fmt: IaCFormat) -> IaCExportResult:
        """Export the graph to the requested IaC format."""
        dispatch = {
            IaCFormat.TERRAFORM: self.export_terraform,
            IaCFormat.CLOUDFORMATION: self.export_cloudformation,
            IaCFormat.KUBERNETES: self.export_kubernetes,
            IaCFormat.DOCKER_COMPOSE: self.export_docker_compose,
            IaCFormat.ANSIBLE: self.export_ansible,
            IaCFormat.PULUMI_PYTHON: self.export_pulumi,
        }
        handler = dispatch.get(fmt)
        if handler is None:
            return IaCExportResult(
                format=fmt,
                warnings=[f"Unsupported format: {fmt.value}"],
            )
        return handler(graph)

    # ---- Terraform ---------------------------------------------------------

    def export_terraform(self, graph: InfraGraph) -> IaCExportResult:
        warnings: list[str] = []
        unsupported: list[str] = []

        main_blocks: list[str] = [_TF_HEADER]

        # Variables for VPC/subnets referenced by resources
        main_blocks.append(textwrap.dedent("""\
            variable "vpc_id" {
              description = "VPC ID for resource deployment"
              type        = string
            }

            variable "subnet_ids" {
              description = "List of subnet IDs"
              type        = list(string)
            }

            # ECS cluster (shared by services)
            resource "aws_ecs_cluster" "main" {
              name = "${var.environment}-faultzero-cluster"

              setting {
                name  = "containerInsights"
                value = "enabled"
              }

              tags = local.common_tags
            }
        """))

        for comp in graph.components.values():
            sid = _sanitize_id(comp.id)
            renderer = _TF_RENDERER.get(comp.type)
            if renderer is not None:
                main_blocks.append(renderer(comp, sid))
            else:
                main_blocks.append(_tf_generic(comp, sid))
                if comp.type == ComponentType.EXTERNAL_API:
                    warnings.append(
                        f"Component '{comp.id}' is an external API and cannot be "
                        "provisioned via Terraform. A placeholder service was generated."
                    )

        content = "\n".join(main_blocks)

        readme = self._generate_readme(
            graph, IaCFormat.TERRAFORM,
            deploy_commands=[
                "terraform init",
                "terraform plan -var-file=terraform.tfvars",
                "terraform apply -var-file=terraform.tfvars",
            ],
        )

        return IaCExportResult(
            format=IaCFormat.TERRAFORM,
            files={"main.tf": content},
            warnings=warnings,
            unsupported_components=unsupported,
            readme=readme,
        )

    # ---- CloudFormation ----------------------------------------------------

    def export_cloudformation(self, graph: InfraGraph) -> IaCExportResult:
        warnings: list[str] = []
        unsupported: list[str] = []

        resource_blocks: list[str] = []
        for comp in graph.components.values():
            sid = _sanitize_id(comp.id).replace("_", "")
            sid = sid[0].upper() + sid[1:]  # PascalCase-ish for CFN
            resource_blocks.append(_cfn_resource(comp, sid))

        header = textwrap.dedent("""\
            AWSTemplateFormatVersion: '2010-09-09'
            Description: >-
              FaultZero auto-generated CloudFormation template.
              Review all resources before deploying.

            Parameters:
              VpcId:
                Type: AWS::EC2::VPC::Id
                Description: VPC for deployment
              SubnetIds:
                Type: List<AWS::EC2::Subnet::Id>
                Description: Subnets for deployment
              Environment:
                Type: String
                Default: production

            Resources:
        """)

        content = header + "\n".join(resource_blocks)

        readme = self._generate_readme(
            graph, IaCFormat.CLOUDFORMATION,
            deploy_commands=[
                "aws cloudformation validate-template --template-body file://template.yaml",
                "aws cloudformation deploy --template-file template.yaml "
                "--stack-name faultzero --parameter-overrides VpcId=vpc-xxx SubnetIds=subnet-xxx",
            ],
        )

        return IaCExportResult(
            format=IaCFormat.CLOUDFORMATION,
            files={"template.yaml": content},
            warnings=warnings,
            unsupported_components=unsupported,
            readme=readme,
        )

    # ---- Kubernetes --------------------------------------------------------

    def export_kubernetes(self, graph: InfraGraph) -> IaCExportResult:
        warnings: list[str] = []
        unsupported: list[str] = []
        files: dict[str, str] = {}

        # Namespace
        ns_content = textwrap.dedent("""\
            apiVersion: v1
            kind: Namespace
            metadata:
              name: faultzero
              labels:
                managed-by: faultzero
        """)
        files["00-namespace.yaml"] = ns_content

        for comp in graph.components.values():
            kname = _sanitize_k8s_name(comp.id)
            blocks: list[str] = []

            if comp.type == ComponentType.DATABASE:
                blocks.append(_k8s_statefulset(comp, kname))
                blocks.append(_k8s_service(comp, kname))
            elif comp.type == ComponentType.LOAD_BALANCER:
                blocks.append(_k8s_deployment(comp, kname))
                blocks.append(_k8s_service(comp, kname, svc_type="LoadBalancer"))
                blocks.append(_k8s_ingress(comp, kname))
            else:
                blocks.append(_k8s_deployment(comp, kname))
                blocks.append(_k8s_service(comp, kname))

            hpa = _k8s_hpa(comp, kname)
            if hpa:
                blocks.append(hpa)

            files[f"{kname}.yaml"] = "\n---\n".join(blocks)

        readme = self._generate_readme(
            graph, IaCFormat.KUBERNETES,
            deploy_commands=[
                "kubectl apply -f 00-namespace.yaml",
                "kubectl apply -f . -n faultzero",
                "kubectl get pods -n faultzero",
            ],
        )

        return IaCExportResult(
            format=IaCFormat.KUBERNETES,
            files=files,
            warnings=warnings,
            unsupported_components=unsupported,
            readme=readme,
        )

    # ---- Docker Compose ----------------------------------------------------

    def export_docker_compose(self, graph: InfraGraph) -> IaCExportResult:
        warnings: list[str] = []
        unsupported: list[str] = []

        services: list[str] = []
        volumes: list[str] = []

        for comp in graph.components.values():
            services.append(_dc_service(comp, graph))
            if comp.type in (ComponentType.DATABASE, ComponentType.STORAGE):
                kname = _sanitize_k8s_name(comp.id)
                volumes.append(f"  {kname}_data:")

        header = textwrap.dedent("""\
            # FaultZero auto-generated Docker Compose configuration
            # Review before running: docker compose up -d

            version: "3.9"

            services:
        """)

        footer_parts = ["\nnetworks:\n  faultzero:\n    driver: bridge\n"]
        if volumes:
            footer_parts.append("volumes:\n" + "\n".join(volumes) + "\n")

        content = header + "\n".join(services) + "\n".join(footer_parts)

        readme = self._generate_readme(
            graph, IaCFormat.DOCKER_COMPOSE,
            deploy_commands=[
                "docker compose up -d",
                "docker compose ps",
                "docker compose logs -f",
            ],
        )

        return IaCExportResult(
            format=IaCFormat.DOCKER_COMPOSE,
            files={"docker-compose.yml": content},
            warnings=warnings,
            unsupported_components=unsupported,
            readme=readme,
        )

    # ---- Ansible -----------------------------------------------------------

    def export_ansible(self, graph: InfraGraph) -> IaCExportResult:
        warnings: list[str] = []
        unsupported: list[str] = []

        tasks: list[str] = []
        for comp in graph.components.values():
            tasks.append(_ansible_task(comp))

        playbook = textwrap.dedent("""\
            # FaultZero auto-generated Ansible playbook
            # Usage: ansible-playbook -i inventory.ini playbook.yml
            ---
            - name: Deploy FaultZero infrastructure
              hosts: all
              become: true
              vars:
                managed_by: faultzero
              tasks:
                - name: Install Docker dependencies
                  ansible.builtin.package:
                    name:
                      - docker.io
                      - python3-docker
                    state: present
                  tags:
                    - setup

                - name: Ensure Docker is running
                  ansible.builtin.service:
                    name: docker
                    state: started
                    enabled: true
                  tags:
                    - setup

        """)
        playbook += "\n".join(f"        {line}" for task in tasks for line in task.splitlines())

        readme = self._generate_readme(
            graph, IaCFormat.ANSIBLE,
            deploy_commands=[
                "ansible-playbook -i inventory.ini playbook.yml --check",
                "ansible-playbook -i inventory.ini playbook.yml",
            ],
        )

        return IaCExportResult(
            format=IaCFormat.ANSIBLE,
            files={"playbook.yml": playbook},
            warnings=warnings,
            unsupported_components=unsupported,
            readme=readme,
        )

    # ---- Pulumi (Python) ---------------------------------------------------

    def export_pulumi(self, graph: InfraGraph) -> IaCExportResult:
        warnings: list[str] = []
        unsupported: list[str] = []

        resource_blocks: list[str] = []
        for comp in graph.components.values():
            sid = _sanitize_id(comp.id)
            resource_blocks.append(_pulumi_resource(comp, sid))

        header = textwrap.dedent("""\
            \"\"\"FaultZero auto-generated Pulumi program (Python).

            Usage:
                pulumi up
            \"\"\"

            import json

            import pulumi
            import pulumi_aws as aws

            config = pulumi.Config()

            common_tags = {
                "managed-by": "faultzero",
                "environment": config.get("environment") or "production",
            }

            # Shared ECS cluster
            ecs_cluster = aws.ecs.Cluster(
                "faultzero-cluster",
                settings=[aws.ecs.ClusterSettingArgs(
                    name="containerInsights",
                    value="enabled",
                )],
                tags=common_tags,
            )
        """)

        content = header + "\n".join(resource_blocks)

        readme = self._generate_readme(
            graph, IaCFormat.PULUMI_PYTHON,
            deploy_commands=[
                "pulumi stack init dev",
                "pulumi up --yes",
                "pulumi stack output",
            ],
        )

        return IaCExportResult(
            format=IaCFormat.PULUMI_PYTHON,
            files={"__main__.py": content},
            warnings=warnings,
            unsupported_components=unsupported,
            readme=readme,
        )

    # ---- Remediation export ------------------------------------------------

    def export_remediation(
        self,
        graph: InfraGraph,
        changes: list[dict[str, Any]],
        fmt: IaCFormat,
    ) -> IaCExportResult:
        """Export only the changes/recommendations as IaC.

        *changes* is a list of dicts describing what to change, e.g.
        ``[{"component_id": "db", "action": "add_replicas", "replicas": 3}]``.
        The method applies those changes to a copy of the graph and exports
        the modified subset.
        """
        # For simplicity, export the full graph in the requested format
        # and add warnings about which components were changed.
        result = self.export(graph, fmt)
        for change in changes:
            cid = change.get("component_id", "unknown")
            action = change.get("action", "modify")
            result.warnings.append(
                f"Remediation applied: {action} on component '{cid}'"
            )
        return result

    # ---- Readme generation -------------------------------------------------

    def _generate_readme(
        self,
        graph: InfraGraph,
        fmt: IaCFormat,
        deploy_commands: list[str] | None = None,
    ) -> str:
        lines = [
            f"# FaultZero IaC Export — {fmt.value}",
            "",
            "Auto-generated infrastructure-as-code from FaultZero topology.",
            "",
            "## Components",
            "",
            f"Total components: {len(graph.components)}",
            "",
            "| Component | Type | Replicas |",
            "|-----------|------|----------|",
        ]
        for comp in graph.components.values():
            lines.append(f"| {comp.name} | {comp.type.value} | {comp.replicas} |")

        lines.append("")
        lines.append("## Deployment")
        lines.append("")

        if deploy_commands:
            lines.append("```bash")
            for cmd in deploy_commands:
                lines.append(cmd)
            lines.append("```")

        lines.append("")
        lines.append("## Important Notes")
        lines.append("")
        lines.append("- Review all generated files before applying to production.")
        lines.append("- Replace placeholder values (passwords, VPC IDs, etc.).")
        lines.append("- Managed by tag: `faultzero`")
        lines.append("")

        return "\n".join(lines)
